export const SAVE_EMAIL = 'SAVE_EMAIL';
export const SAVE_NAME = 'SAVE_NAME';
export const SAVE_SCORE = 'SAVE_SCORE';
export const GENERATE_RANDOM_INDEX = 'GENERATE_RANDOM_INDEX';
export const PUSH_ANSWERS_TO_GLOBAL_STATE = 'PUSH_ANSWERS_TO_GLOBAL_STATE';
